included:
  - Sources
disabled_rules:
  - opening_brace
  - trailing_comma
identifier_name:
  excluded:
    - id
line_length:
  warning: 120
  error: 120
trailing_whitespace:
  severity:
    error
vertical_whitespace:
  severity:
    error
opt_in_rules:
  - force_unwrapping
